"use client";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import {
  createContext,
  Dispatch,
  SetStateAction,
  useContext,
  useEffect,
  useState,
} from "react";
import ProductsArray, { Product } from "./ProductsArray";
import CartComponent from "./components/Cart/CartComponent";
const manrope = Manrope({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const MyContext = createContext<Props>({
  amount: 0,
  setAmount: () => {},
  isOpen: false,
  setIsOpen: () => {},
  Products: [],
  setProducts: () => {},
  isCartOpen: false,
  setIsCartOpen: () => {},
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [amount, setAmount] = useState<number>(0);
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const [isCartOpen, setIsCartOpen] = useState<boolean>(false);
  const Productstemp = ProductsArray();
  const [Products, setProducts] = useState<Product[]>(Productstemp);

  return (
    <MyContext.Provider
      value={{
        amount,
        setAmount,
        isOpen,
        setIsOpen,
        Products,
        setProducts,
        isCartOpen,
        setIsCartOpen,
      }}
    >
      <html lang="en">
      <body
   
    className={manrope.className}
  >
    <div  style={
      isCartOpen
        ? {
            backgroundColor: "#191919",
            filter:"blur(3.5px)"
           }
        : {}
    }>
    {children}

    </div>
          {<CartComponent />}
        </body>
      </html>
    </MyContext.Provider>
  );
}

type Props = {
  amount: number;
  setAmount: Dispatch<SetStateAction<number>>;
  isOpen: boolean;
  setIsOpen: Dispatch<SetStateAction<boolean>>;
  Products: Product[];
  setProducts: Dispatch<SetStateAction<Product[]>>;
  isCartOpen: boolean;
  setIsCartOpen: Dispatch<SetStateAction<boolean>>;
};
